Title =  "blog.dornea.nu"
defaultContentLanguage = "en"
languageCode = "en-us"
BaseUrl = "https://blog.dornea.nu"
Theme = "er"
MetaDataFormat =  "yaml"
CanonifyUrls =  true
BuildDrafts =  false
# Replaced deprecated pagination settings
[pagination]
path =  "p"
pagerSize = 10
DisablePathToLower =  false
HasCJKLanguage = true
PreserveTaxonomyNames = false
UglyUrls = false
PygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodefences = true
# pygmentsCodefencesGuessSyntax = true
DefaultContentLanguage = "en"
# disqusShortname = "dorneanu"
# publishDir = "docs"

copyright="2009-2025 Victor Dorneanu - All rights reserved"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    style = 'emacs'
    tabWidth = 4

# Make sure we use Goldmark
# https://ox-hugo.scripter.co/doc/goldmark/
[markup.goldmark.renderer]
  unsafe = true


[Params.Author]
  name="Victor Dorneanu"

[Params.Social]
  # Add your social media accounts here if needed
  # facebook = "yourusername"
  # twitter = "yourusername"
  # github = "yourusername"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[permalinks]
posts = "/:year/:month/:day/:title"
notes = "/notes/:title"
gists = "/gists/:title"

[Params]
  Introduce = "blog.dornea.nu"
  Description = "Hack, code and drink some țuică. Personal blog of Victor Dorneanu."
  Keywords =  ""
  Subtitle = ""
  Imglogo = "/img/logo.png"
  AuthorImg = "/img/author.jpg"
  DateFormat = "2006-01-02"
  YearFormat = "2006"
  MonthFormat = "01-02"
  #BaiduStatsId = "0b07433b4ab8d587dae7d34e71973839"
  #QQStatsId = "58416275"
  #RevolverMapId = "5b4f2ucxar6"
  Fancybox = true
  # showTagCloud = true
  # showtoc = true

  # For hermit theme
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  # description = ""
  # images = [""]
  themeColor = "#494f5c"

  homeSubtitle = "braindumps about almost everything"
  footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
  # bgImg = ""  # Homepage background-image URL

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  # gitUrl = "https://github.com/username/repository/commit/"

  # Toggling this option needs to rebuild SCSS, requires Hugo extended version
  justifyContent = false  # Set "text-align: justify" to `.content`.
  relatedPosts = true  # Add a related content section to all single posts page
  code_copy_button = false # Turn on/off the code-copy-button for code-fields
  customCSS = ["css/custom.css", "css/syntax.css"]


# This was duplicating the author info - removed
# [Params.Author] is defined above

[[Menu.Main]]
  Name = "Home"
  Pre = "home"
  URL = "/"
  Weight = 1
[[Menu.Main]]
  Name = "About"
  Pre = "code"
  URL = "http://dornea.nu"
  Weight = 5
[[Menu.Main]]
  Name = "Tags"
  Pre = "book"
  URL = "/tags"
  Weight = 6
[[Menu.Main]]
  Name = "RSS"
  Pre = "book"
  URL = "/feed.xml"
  Weight = 6
# [[Menu.Main]]
#   Name = "Bookmarks"
#   Pre = "book"
#   URL = "/bookmarks"
#   Weight = 7
[[Menu.Main]]
  Name = "Zettelkasten"
  Pre = "sticky-note"
  URL = "https://brainfck.org"
  Weight = 8
# [[Menu.Main]]
#   Name = "Bookmarks"
#   Pre = "code"
#   URL = "https://brainfck.org/bookmarks.html"
#   Weight = 10
# [[Menu.Main]]
#   Name = "Books"
#   Pre = "book"
#   URL = "https://brainfck.org/bib.html"
#   Weight = 15
# [[Menu.Main]]
#   Name = "Notes"
#   Pre = "sticky-note"
#   URL = "/notes"
#   Weight = 20


[deployment]
order = [".jpg$", ".gif$"]

# [[deployment.targets]]
# name = "brainfck"
# URL="s3://brainfck.org?region=eu-central-1"

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true

[outputs]
home = [ "HTML", "RSS"]

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"
